AWSTemplateFormatVersion: '2010-09-09'
Description: AWS SNS Topic for Grafana Alerts

Resources:
  GrafanaAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: aws-grafana-alert-topic

Outputs:
  GrafanaAlertTopicArn:
    Description: SNS Topic ARN
    Value: !Ref GrafanaAlertTopic
    Export:

      Name: GrafanaAlertTopicArn
